### PR TITLE
Updated UI style, new icon, other tweaks

### PR DESCRIPTION
**Pull request by sebj**
Hi,

First up, thanks for making this app!

Changes I've made in this fork:
- Updated icon to use the Google Assistant logo (below)
- Update the UI style to match Google's Assistant (below)
  - Cards now use a title and subtext format
  - Accessibility and Allo required cards show icons
  - The card mentioning setting the assist app now goes straight to the settings screen to set the default Assist app when tapped
- About menu item (currently goes to Github when tapped, can be changed)
- Other tidying: Gradle and other dependencies have been updated, testing modules have been removed for now, README slightly changed

New Icon

New Main Screen UI

– Seb

### CODE REVIEW

**Comment by arunkumar9t2** [comment]
Thank you for this! Looks awesome. I ll merge it soon and try to compile a 1.1 release.

**Comment by CDAGaming** [comment]
@sebj , Gonna update your fork if thats ok with you

https://github.com/arunkumar9t2/allistant/issues/4 : More info

**Comment by sebj** [comment]
@CDAGaming Sounds good to me (thanks) 😃 , although creates a bit of confusion with pull requests here. @arunkumar9t2 could merge soon (I hope!)

**Comment by CDAGaming** [comment]
@sebj, Hopefully and there is one last thing I'd like to add which is an Android keystone to make release apk's instead of debug apk. Main reason is that the realease apk's are supposed to be more optimized during compiling in android studio. However to do so, I'd need info to put into it from the OP

**Comment by CDAGaming** [comment]
@sebj, there's only been one known issue with the app as of now where it takes a few seconds for Allistant to go into the Google assistant conversation. The release optimizations might speed up the times, possibly

**Comment by sebj** [comment]
@CDAGaming Generally, Android keystores should not be included in public repositories as it's a pretty big security risk ([1](http://stackoverflow.com/questions/17491794/is-there-any-reason-i-shouldnt-store-my-keystore-in-version-control), [2](https://commonsware.com/blog/2013/01/28/what-not-to-put-in-your-repo.html), etc), although there's nothing stopping you from building and seeing if the release build is any faster for you locally. I'm unsure how much of a speed boost you're likely to see, but worth a try.

**Comment by arunkumar9t2** [comment]
@sebj I have finally merged the changes - took really long enough, sorry. I plan to add some new features targeting 25 and then release version 1.1.

**Comment by sebj** [comment]
Awesome! Thanks for merging! 🙂




On Tue, Jan 24, 2017 at 11:50 PM +0000, "Arunkumar" <notifications@github.com> wrote:












@sebj I have finally merged the changes - took really long enough, sorry. I plan to add some new features targeting 25 and then release version 1.1.

**Comment by CDAGaming** [comment]
@arunkumar9t2 My Pull Request was with @sebj Features here, and Updating all dependencies up to their latest versions(As of January 2016)as they were very outdated on this pull request & Support for Android Nougat. I may have to re-update the dependencies but you should be able to merge mine soon

**Pull request merged**
